"""
AerodromeSlipstreamUsdcCbbtcYield Strategy Package.

Generated by: almanak strat new
"""

from strategy import AerodromeSlipstreamUsdcCbbtcYieldStrategy

__all__ = [
    "AerodromeSlipstreamUsdcCbbtcYieldStrategy",
]
